version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4.2.1
    restart: always
    ports:
      - 27017:27017
    networks:
      - data-store
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - data-store
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - data-store

networks:
  data-store:
    driver: bridge
