version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4.2.1
    restart: always
    ports:
      - 27017:27017
    networks:
      - database
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_root
      MONGO_INITDB_ROOT_PASSWORD: mongo_root
    volumes:
      - ./mongo.entrypoint.js:/docker-entrypoint-initdb.d/entrypoint.js
  
  redis:
    container_name: redis
    image: redis:6.0-alpine
    command: redis-server --requirepass redis
    ports:
      - 6379:6379
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_root
      ME_CONFIG_MONGODB_URL: mongodb://mongo_root:mongo_root@localhost:27017/

networks:
  database:
    driver: bridge